#!/usr/bin/env python3
"""Split a flat $readmemh program image into even/odd bank MIF files (D022),
or emit one flat MIF with --single (D023, for the dmem data image).

The banked M9K instruction ROM (rtl/mem/imem_banked.v) holds word i in bank
(i & 1) at bank address (i >> 1) — even words in imem_even.mif, odd words in
imem_odd.mif. This convention is stated verbatim in the RTL header; keep the
two in sync. dmem (rtl/mem/dmem.v) is a single unbanked RAM, hence --single.

Input:  $readmemh format as scripts/bin2hex.py emits it — one 8-hex-digit
        32-bit little-endian word per line; blank lines and '//' comments
        are tolerated.
Output: Quartus .mif per bank (WIDTH=32, DEPTH=depth_words/2, HEX radixes).
        The image is padded to the full depth with --pad (default NOP,
        0x00000013) so board behavior on a runaway PC matches the Verilator
        arm's NOP-fill.
--check re-parses both emitted MIFs, re-interleaves them, and compares
        word-for-word against the padded input image (round-trip guard
        against word-order/bank-swap bugs).
"""
import argparse
import re
import sys


def read_hex(path):
    """Parse a $readmemh file into a list of ints."""
    words = []
    with open(path) as f:
        for lineno, line in enumerate(f, 1):
            line = line.split("//")[0].strip()
            if not line:
                continue
            if not re.fullmatch(r"[0-9a-fA-F]{1,8}", line):
                sys.exit(f"{path}:{lineno}: not a hex word: {line!r}")
            words.append(int(line, 16))
    return words


def write_mif(path, bank, pad, src_name, nwords_prog):
    """Emit one bank as a .mif; program prefix explicit, uniform tail as a range."""
    depth = len(bank)
    # last index that differs from the pad value (-1 if bank is all-pad)
    last = -1
    for i, w in enumerate(bank):
        if w != pad:
            last = i
    # everything at index <= last is emitted explicitly; also emit explicit
    # entries up to the program's own words even when they equal the pad, so
    # the file visibly mirrors the program prefix.
    explicit = max(last + 1, min(nwords_prog, depth))
    awidth = max(1, len(f"{depth - 1:X}"))
    with open(path, "w") as out:
        out.write(f"-- generated by scripts/hex2mif.py from {src_name}"
                  f" -- do not hand-edit (see 'make mif')\n")
        out.write(f"DEPTH = {depth};\n")
        out.write("WIDTH = 32;\n")
        out.write("ADDRESS_RADIX = HEX;\n")
        out.write("DATA_RADIX = HEX;\n")
        out.write("CONTENT BEGIN\n")
        for i in range(explicit):
            out.write(f"{i:0{awidth}X} : {bank[i]:08X};\n")
        if explicit < depth:
            out.write(f"[{explicit:0{awidth}X}..{depth - 1:0{awidth}X}]"
                      f" : {pad:08X};\n")
        out.write("END;\n")


def read_mif(path):
    """Parse back a .mif written by write_mif (also tolerates generic MIFs)."""
    depth = None
    mem = {}
    entry = re.compile(r"^([0-9a-fA-F]+)\s*:\s*([0-9a-fA-F]+);$")
    rng = re.compile(r"^\[([0-9a-fA-F]+)\.\.([0-9a-fA-F]+)\]\s*:\s*([0-9a-fA-F]+);$")
    in_content = False
    with open(path) as f:
        for lineno, line in enumerate(f, 1):
            line = line.split("--")[0].strip()
            if not line:
                continue
            m = re.match(r"^DEPTH\s*=\s*(\d+);$", line)
            if m:
                depth = int(m.group(1))
                continue
            if re.match(r"^(WIDTH|ADDRESS_RADIX|DATA_RADIX)\s*=", line):
                continue
            if line.upper() == "CONTENT BEGIN":
                in_content = True
                continue
            if line.upper() == "END;":
                in_content = False
                continue
            if not in_content:
                sys.exit(f"{path}:{lineno}: unexpected line outside CONTENT: {line!r}")
            m = entry.match(line)
            if m:
                mem[int(m.group(1), 16)] = int(m.group(2), 16)
                continue
            m = rng.match(line)
            if m:
                lo, hi, val = (int(m.group(1), 16), int(m.group(2), 16),
                               int(m.group(3), 16))
                for a in range(lo, hi + 1):
                    mem[a] = val
                continue
            sys.exit(f"{path}:{lineno}: unparsable MIF content line: {line!r}")
    if depth is None:
        sys.exit(f"{path}: no DEPTH found")
    return [mem.get(a, 0) for a in range(depth)]


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("hex_in", help="flat $readmemh image (bin2hex.py output)")
    ap.add_argument("mif_even", help="output MIF for even words (word 0,2,4,...)"
                    " — with --single: the one output MIF")
    ap.add_argument("mif_odd", nargs="?", default=None,
                    help="output MIF for odd words (omit with --single)")
    ap.add_argument("--single", action="store_true",
                    help="no banking: emit the whole image as one MIF (dmem)")
    ap.add_argument("--depth-words", type=int, default=1024,
                    help="total memory depth in words (default 1024 = 4 KB)")
    ap.add_argument("--pad", type=lambda s: int(s, 0), default=0x00000013,
                    help="fill value for unused words (default NOP 0x00000013)")
    ap.add_argument("--check", action="store_true",
                    help="re-parse the emitted MIFs and verify the round trip")
    args = ap.parse_args()

    if args.single == (args.mif_odd is not None):
        sys.exit("pass exactly one output with --single, exactly two without")
    if not args.single and args.depth_words % 2:
        sys.exit("--depth-words must be even (two equal banks)")
    prog = read_hex(args.hex_in)
    if len(prog) > args.depth_words:
        sys.exit(f"{args.hex_in}: {len(prog)} words exceeds memory depth "
                 f"{args.depth_words}")
    image = prog + [args.pad] * (args.depth_words - len(prog))

    if args.single:
        write_mif(args.mif_even, image, args.pad, args.hex_in, len(prog))
        if args.check:
            back = read_mif(args.mif_even)
            if back != image:
                bad = next(i for i, (a, b) in enumerate(zip(back, image))
                           if a != b)
                sys.exit(f"check FAILED: word {bad}: mif={back[bad]:08x} "
                         f"hex={image[bad]:08x}")
            print(f"hex2mif: {len(prog)} data words -> {args.mif_even} "
                  f"({args.depth_words} words), round-trip check OK")
        else:
            print(f"hex2mif: {len(prog)} data words -> {args.mif_even}")
        return

    even = image[0::2]
    odd = image[1::2]
    write_mif(args.mif_even, even, args.pad, args.hex_in, (len(prog) + 1) // 2)
    write_mif(args.mif_odd, odd, args.pad, args.hex_in, len(prog) // 2)

    if args.check:
        back_e = read_mif(args.mif_even)
        back_o = read_mif(args.mif_odd)
        if len(back_e) != len(even) or len(back_o) != len(odd):
            sys.exit("check FAILED: bank depth mismatch on re-parse")
        rebuilt = [w for pair in zip(back_e, back_o) for w in pair]
        if rebuilt != image:
            bad = next(i for i, (a, b) in enumerate(zip(rebuilt, image)) if a != b)
            sys.exit(f"check FAILED: word {bad}: mif={rebuilt[bad]:08x} "
                     f"hex={image[bad]:08x}")
        print(f"hex2mif: {len(prog)} program words -> {args.mif_even} + "
              f"{args.mif_odd} ({args.depth_words // 2} words/bank), "
              "round-trip check OK")
    else:
        print(f"hex2mif: {len(prog)} program words -> {args.mif_even} + "
              f"{args.mif_odd}")


if __name__ == "__main__":
    main()
